### ISSUE TITLE
In the README.md, add a link to the live deployed JS Zoo?

### ISSUE THREAD

**Issue by replaceafill** [novawebdevelopment/jszoo#1]

**Comment by jelkner** [comment]
Hmmm... I don't know how to add relative links to the README.md  I tried, but get a 404 error.  Any chance you could show me the way, Mr. Cerna?

**Comment by kjcole** [comment]
On Fri, Nov 4, 2016 at 12:50 PM, Jeff Elkner <notifications@github.com> wrote:
>
> Hmmm... I don't know how to add relative links to the README.md I tried, but get a 404 error. Any chance you could show me the way, Mr. Cerna?

[Text](URL)

Markdown Syntax Guide

http://daringfireball.net/projects/markdown/basics

**Comment by kjcole** [comment]
I don't know that you can add relative links, and a relative link from
the README.md wouldn't do you any good (unless the README.md) is on
the same site as the live Zoo.  So, an absolute link in the form

[Text](URL)

where URL is a full URL pointing to the live site should work.

Meanwhile note there is a similar issue pending for the CSS Zoo.

**Comment by jelkner** [comment]
Not very helpful, Mr. Cole.  I don't think you looked at what I did. I know the [Text](URL) pattern.  I just don't know the URL.  Marco told me there is a way to view html repos rendered as web pages, but I don't know how.  Why don't you fix it and show me? ;-)

**Comment by kjcole** [comment]
According to ​http://stackoverflow.com/a/12233684/447830

The most comfortable way to preview HTML files on GitHub is to go to
http://htmlpreview.github.com/ or just prepend it to the original URL,
i.e.:
http://htmlpreview.github.com/?https://github.com/bartaz/impress.js/blob/master/index.html
